In [85]:
import numpy as np
import pandas as pd
import csv

In [86]:
data = pd.read_csv('dataset.csv', keep_default_na = False)

In [87]:
data

,BRAND,COLOUR,CONDITION,CONTRACT,MEMORY,MOBOS,MODEL,PRICE
0,Samsung,gray,like new,Sprint,256,android,S8 PLUS,$270
1,Blu,red,like new,Unlocked,16,android,Y85,$50
2,Samsung,unknow,Unknown,Verizon,0,android,S10 plus,$745
3,Apple,unknow,like new,T-Mobile,64,apple iOS,iPhone 8 Plus,$400
4,Samsung,white,excellent,Unlocked,64,android,NOTE 8,$70
...,...,...,...,...,...,...,...,...
10479,Asus,unknow,fair,Unlocked,0,android,Rog,$450
10480,Apple,unknow,good,Unlocked,64,apple iOS,Iphone X,$450
10481,Apple,black,like new,At&t,64,apple iOS,6 PLUS,$235
10482,Lg,black,like new,Sprint,64,android,V20,$120
10483,Lg,black,like new,Sprint,32,android,V20,$120

In [88]:
data['PRICE']

0        $270
1         $50
2        $745
3        $400
4         $70
         ...
10479    $450
10480    $450
10481    $235
10482    $120
10483    $120
Name: PRICE, Length: 10484, dtype: object

In [89]:
prices = np.ndarray(data['PRICE'].shape)
c = 0

for p in data['PRICE']:
	prices[c] = int(p.split('$')[1])
	c+=1

data['PRICE'] = prices

In [90]:
data

,BRAND,COLOUR,CONDITION,CONTRACT,MEMORY,MOBOS,MODEL,PRICE
0,Samsung,gray,like new,Sprint,256,android,S8 PLUS,270.0
1,Blu,red,like new,Unlocked,16,android,Y85,50.0
2,Samsung,unknow,Unknown,Verizon,0,android,S10 plus,745.0
3,Apple,unknow,like new,T-Mobile,64,apple iOS,iPhone 8 Plus,400.0
4,Samsung,white,excellent,Unlocked,64,android,NOTE 8,70.0
...,...,...,...,...,...,...,...,...
10479,Asus,unknow,fair,Unlocked,0,android,Rog,450.0
10480,Apple,unknow,good,Unlocked,64,apple iOS,Iphone X,450.0
10481,Apple,black,like new,At&t,64,apple iOS,6 PLUS,235.0
10482,Lg,black,like new,Sprint,64,android,V20,120.0
10483,Lg,black,like new,Sprint,32,android,V20,120.0

In [91]:
data.to_csv('final_data.csv', header=True)

In [92]:
data.MOBOS.unique()

array(['android', 'apple iOS', 'other', 'apple ios', 'windows mobile'],
      dtype=object)

In [93]:
os = data['MOBOS']
c = 0
counter=0
for p in data['MOBOS']:
    if(p=="apple iOS"):
        os[c] = 'apple ios'
        counter+=1
        c+=1
    else:
        os[c]=p
        c+=1
        
   #c+=1

data['MOBOS'] = os
print(counter)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

7122

In [94]:
data.MOBOS.unique()

array(['android', 'apple ios', 'other', 'windows mobile'], dtype=object)

In [95]:
data.to_csv('final_data.csv', header=True)

In [96]:
data.CONDITION.unique()

array(['like new', 'Unknown', 'excellent', 'good', 'fair', 'Perfect',
       'Good', 'salvage'], dtype=object)

In [97]:
cond = np.ndarray(data['CONDITION'].shape)

c = 0

for p in data['CONDITION']:
    if(p=='salvage'):
        cond[c] = 1
    elif(p=='fair'):
        cond[c] = 2
    elif(p=='Unknown'):
        cond[c] = 3
    elif(p=='like new' or p=='good' ):
        cond[c] = 4
    elif(p=='excellent' or p=='Perfect' ):
        cond[c] = 5
    else:
        cond[c] = 3
    c+=1
        
   #c+=1

data['CONDITION'] = cond

In [98]:
data

,BRAND,COLOUR,CONDITION,CONTRACT,MEMORY,MOBOS,MODEL,PRICE
0,Samsung,gray,4.0,Sprint,256,android,S8 PLUS,270.0
1,Blu,red,4.0,Unlocked,16,android,Y85,50.0
2,Samsung,unknow,3.0,Verizon,0,android,S10 plus,745.0
3,Apple,unknow,4.0,T-Mobile,64,apple ios,iPhone 8 Plus,400.0
4,Samsung,white,5.0,Unlocked,64,android,NOTE 8,70.0
...,...,...,...,...,...,...,...,...
10479,Asus,unknow,2.0,Unlocked,0,android,Rog,450.0
10480,Apple,unknow,4.0,Unlocked,64,apple ios,Iphone X,450.0
10481,Apple,black,4.0,At&t,64,apple ios,6 PLUS,235.0
10482,Lg,black,4.0,Sprint,64,android,V20,120.0
10483,Lg,black,4.0,Sprint,32,android,V20,120.0

In [100]:
data.to_csv('final_data.csv', header=True, index=False)